base_config: ../trainer-replica.yaml
exp_name: replica/garage
bound_min: [-18.0, -20.0, -5.5]
bound_max: [10.0, 0.0, 1.5]
data:
    dataset_args:
        data_path: "data/garage/replica"
        min_depth: 0.3
        max_depth: 20.0
frame_downsample: 10
key_frame_set:
    insert_interval: 20
    selection_window_size: 8
model:
    octree_cfg:
        resolution: 0.10
        tree_depth: 9
        semi_sparse_depth: 5
        init_voxel_num: 1200000
        insertion_threshold: 20
sample_rays:
    depth_min: 0.3
    depth_max: 20.0
    sigma_s: 0.03
    surface_margin: 0.09
criterion:
    perturbation_loss_exp_penalty: 10.0
grad_clip: 0   # clip gradient norm; set to 0 to disable
batch_size: 20480000
#detect_nan: true  # uncomment to enable slow but detailed NaN tracing
mesh_resolution: 0.05
